Module not found: Can't resolve '@opentelemetry/exporter-jaeger' in '/vercel/path0/node_modules/@opentelemetry/sdk-node/build/src'
[Error: Failed to collect configuration for /auth/register] {
  [cause]: ReferenceError: jsx is not defined
      at 64943 (.next/server/app/auth/register/page.js:1:2199)
      at Function.t (.next/server/webpack-runtime.js:1:143)
}
> Build error occurred
[Error: Failed to collect page data for /auth/register] {
  type: 'Error'
}
Error: Command "npm run build" exited with 1
Exiting build container